### PR TITLE
Jms changes

### PR DESCRIPTION
**Pull request by thomasfanto**

### CODE REVIEW

**Comment by jemConsid** [comment]
test me

**Comment by thomasfanto** [comment]
test me

**Comment by thomasfanto** [comment]
test me

**Comment by jemConsid** [comment]
test me

**Comment by thomasfanto** [comment]
test me

**Comment by peerik** [comment]
test me

**Comment by jemConsid** [comment]
test me

**Comment by jemConsid** [comment]
test me

**Pull request merged**
